remote_theme: jekyll/minima
google_site_verification: "C-lY-Xpcx8_KgeKX9rJ3u_rIjnI-aUyY0GZd9S8Btw4"
title: ""
description: "neon-aiart.github.io: Profile and Projects Showcase"
header_pages: []

markdown: commonmark
# commonmarker:
#   options: [RAW_HTML, UNSAFE]
kramdown:
  input: GFM # GitHub Flavored Markdownを使用
  parse_block_html: true
#   hard_wrap: false
  syntax_highlighter: rouge # disableにするより、こっちが標準的
#   syntax_highlighter_opts:
#     disable: true # タグがコードブロック扱いされるのを防ぐ
